### ISSUE TITLE
[SimMarket/Vendors] Requested Finale Scenarios

### ISSUE THREAD

**Issue by ldreessen** [hpi-epic/BP2021#418]
The last weekly resulted in a finale decision for the market scenarios. The existing scenarios will remain, but in addition to that our simulation should provide more scenarios.
As Rainer we want to have the possibility to play through the following scenarios:

- [x] Monopoly

- [x] Duopoly (rule-based against RL)

- [x] Oligopoly (4 rule-based against RL) #419 

- [x] RL Duopoly (RL against RL) #421
